name: LL
markdown: redcarpet
pygments: true
production_url: http://lloydsarm.com/

author:
 name: Lloyd Thompson
 email: ll@lloydsarm.com

categoryNames:
 ux: "User Experience"
 fashion: "Shoes & Fashion"
 food-and-drink: "Food & Drink"
 features: "Features"
